insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'user001',1, NOW()-200 , '서울 구로구 신도림동 692','248호','젓가락 2개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'user008',8, NOW()-200 , '서울 마포구 서교동 369-5','93호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user005',5, NOW()-200 , '서울 양천구 신정동 282-10','49호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'user009',9, NOW()-200 , '서울 마포구 서교동 369-1','39호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'user009',9, NOW()-200 , '서울 구로구 신도림동 338','55호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'user001',1, NOW()-200 , '서울 구로구 구로동 110-5','29호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'user005',5, NOW()-200 , '서울 구로구 구로동 1267','257호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'user004',4, NOW()-200 , '서울 마포구 합정동 427-5','270호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'user004',4, NOW()-200 , '서울 마포구 동교동 163-9','82호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'user008',8, NOW()-200 , '서울 마포구 동교동 165-8','65호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'user001',1, NOW()-200 , '서울 마포구 상수동 90-2','17호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'user010',10, NOW()-200 , '서울 구로구 신도림동 338','97호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'user006',6, NOW()-200 , '서울 구로구 구로동 501-5','231호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'user003',3, NOW()-200 , '서울 구로구 구로동 170-10','226호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'user010',10, NOW()-200 , '서울 마포구 합정동 387-21','58호','젓가락 3개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user006',6, NOW()-200 , '서울 구로구 구로동 98-1','158호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'user008',8, NOW()-200 , '서울 마포구 합정동 473','294호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'user002',2, NOW()-200 , '서울 구로구 구로동 212-8','150호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'user010',10, NOW()-200 , '서울 마포구 서교동 369-10','215호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'user009',9, NOW()-200 , '서울 구로구 구로동 29-22','88호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'user005',5, NOW()-200 , '서울 마포구 서교동 444-2','186호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'user001',1, NOW()-200 , '서울 구로구 구로동 426-167','290호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'user007',7, NOW()-200 , '서울 구로구 신도림동 692','51호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'user004',4, NOW()-200 , '서울 마포구 합정동 393-7','239호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'user002',2, NOW()-200 , '서울 마포구 상수동 314-10','146호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'user005',5, NOW()-200 , '서울 구로구 구로동 87-1','150호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'user001',1, NOW()-200 , '서울 마포구 망원동 416-49','239호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'user010',10, NOW()-200 , '서울 마포구 상수동 310-14','174호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user007',7, NOW()-200 , '서울 마포구 서교동 369-44','65호','젓가락 4개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'user010',10, NOW()-200 , '서울 마포구 상수동 90-8','249호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'user001',1, NOW()-200 , '서울 구로구 신도림동 437-1','61호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'user007',7, NOW()-200 , '서울 마포구 상수동 314-11','214호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'user007',7, NOW()-200 , '서울 마포구 상수동 71-15','251호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user008',8, NOW()-200 , '서울 마포구 망원1동 414-20','179호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'user009',9, NOW()-200 , '서울 마포구 상수동 339-9','104호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'user005',5, NOW()-200 , '서울 구로구 구로동 40-10','237호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'user010',10, NOW()-200 , '서울 마포구 상수동 314-8','85호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'user003',3, NOW()-200 , '서울 구로구 구로동 41-7','298호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'user007',7, NOW()-200 , '서울 영등포구 대림동 1116-15','58호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'user003',3, NOW()-200 , '서울 마포구 상수동 304-1','24호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'user010',10, NOW()-200 , '서울 마포구 합정동 370-8','139호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'user003',3, NOW()-200 , '서울 구로구 신도림동 337','167호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'user001',1, NOW()-200 , '서울 구로구 구로동 74-30','61호','젓가락 5개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'user008',8, NOW()-200 , '서울 구로구 신도림동 648','148호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user002',2, NOW()-200 , '서울 마포구 서교동 371-3','56호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user008',8, NOW()-200 , '서울 구로구 구로동 313-49','9호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'user010',10, NOW()-200 , '서울 마포구 상수동 146-6','7호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'user001',1, NOW()-200 , '서울 구로구 신도림동 437-1','267호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'user002',2, NOW()-200 , '서울 마포구 상수동 146-18','32호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'user008',8, NOW()-200 , '서울 구로구 구로동 528-7','49호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'user008',8, NOW()-200 , '서울 구로구 신도림동 292-247','56호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user001',1, NOW()-200 , '서울 마포구 합정동 367-9','290호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'user003',3, NOW()-200 , '서울 구로구 신도림동 338','3호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'user009',9, NOW()-200 , '서울 구로구 신도림동 292-32','185호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'user001',1, NOW()-200 , '서울 마포구 합정동 472','235호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user006',6, NOW()-200 , '서울 구로구 구로동 1262','158호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user002',2, NOW()-200 , '서울 마포구 상수동 92-2','41호','젓가락 6개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'user003',3, NOW()-200 , '서울 구로구 구로동 770-40','101호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'user010',10, NOW()-200 , '서울 구로구 신도림동 337','112호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'user006',6, NOW()-200 , '서울 마포구 서교동 364-22','117호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'user003',3, NOW()-200 , '서울 마포구 서교동 363-21','169호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'user006',6, NOW()-200 , '서울 마포구 상수동 314-11','239호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'user005',5, NOW()-200 , '서울 마포구 망원동 377-1','135호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'user010',10, NOW()-200 , '서울 마포구 합정동 393-20','40호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'user003',3, NOW()-200 , '서울 마포구 합정동 393-15','48호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'user009',9, NOW()-200 , '서울 구로구 구로동 27-4','121호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'user010',10, NOW()-200 , '서울 마포구 성산동 253-16','219호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'user007',7, NOW()-200 , '서울 마포구 상수동 327-7','77호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'user006',6, NOW()-200 , '서울 구로구 구로동 409-56','233호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user002',2, NOW()-200 , '서울 구로구 신도림동 292-44','269호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'user003',3, NOW()-200 , '서울 마포구 성산동 252-1','278호','젓가락 7개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'user009',9, NOW()-200 , '서울 마포구 상수동 153-4','266호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'user009',9, NOW()-200 , '서울 마포구 서교동 356-3','197호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user004',4, NOW()-200 , '서울 구로구 구로동 603-9','10호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'user006',6, NOW()-200 , '서울 구로구 구로동 544','191호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'user005',5, NOW()-200 , '서울 구로구 고척동 66-2','201호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'user001',1, NOW()-200 , '서울 구로구 신도림동 337','42호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'user009',9, NOW()-200 , '서울 마포구 망원동 425-33','237호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'user005',5, NOW()-200 , '서울 마포구 서교동 441-17','279호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'user008',8, NOW()-200 , '서울 구로구 구로동 1126-35','146호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'user003',3, NOW()-200 , '서울 구로구 신도림동 648','245호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'user002',2, NOW()-200 , '서울 마포구 성산동 533-1','76호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'user006',6, NOW()-200 , '서울 구로구 구로동 186-7','272호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'user001',1, NOW()-200 , '서울 마포구 서교동 360-17','65호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'user004',4, NOW()-200 , '서울 마포구 서교동 476-19','288호','젓가락 8개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'user004',4, NOW()-200 , '서울 구로구 신도림동 639','25호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'user001',1, NOW()-200 , '서울 마포구 상수동 327-7','91호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user006',6, NOW()-200 , '서울 마포구 합정동 473','197호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'user004',4, NOW()-200 , '서울 마포구 동교동 200-24','195호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'user010',10, NOW()-200 , '서울 구로구 구로동 94-10','141호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user001',1, NOW()-200 , '서울 구로구 신도림동 435-10','61호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'user007',7, NOW()-200 , '서울 마포구 서교동 402-5','103호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user008',8, NOW()-200 , '서울 마포구 서교동 332-33','6호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'user009',9, NOW()-200 , '서울 마포구 망원동 485-10','122호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'user005',5, NOW()-200 , '서울 구로구 구로동 486-7','247호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'user010',10, NOW()-200 , '서울 마포구 서교동 476-18','54호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'user005',5, NOW()-200 , '서울 구로구 신도림동 694','41호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'user001',1, NOW()-200 , '서울 마포구 상수동 310-20','10호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'user007',7, NOW()-200 , '서울 마포구 서교동 343-2','234호','젓가락 9개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'user010',10, NOW()-200 , '서울 구로구 고척동 85-15','58호','우유빼고 주세요' );


insert into order_menu ( orderlist_No, menu_No, count) values ( 1 , 28 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 1 , 338 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 1 , 391 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 2 , 313 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 3 , 13 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 3 , 29 , 2) ;
 insert into order_menu ( orderlist_No, menu_No, count) values ( 3 , 199 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 4 , 63 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 4 , 69 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 4 , 380 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 5 , 149 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 5 , 313 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 6 , 46 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 6 , 202 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 6 , 221 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 7 , 105 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 7 , 229 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 7 , 271 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 7 , 290 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 7 , 362 , 2) ;
 insert into order_menu ( orderlist_No, menu_No, count) values ( 7 , 394 , 4) ; 
 insert into order_menu ( orderlist_No, menu_No, count) values ( 8 , 191 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 8 , 243 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 8 , 244 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 8 , 396 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 9 , 28 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 9 , 44 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 9 , 173 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 9 , 391 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 10 , 40 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 10 , 112 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 10 , 168 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 10 , 179 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 11 , 69 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 11 , 215 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 11 , 380 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 12 , 63 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 12 , 69 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 12 , 215 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 12 , 380 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 13 , 69 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 13 , 380 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 14 , 111 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 14 , 269 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 15 , 18 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 15 , 313 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 16 , 13 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 16 , 199 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 17 , 34 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 17 , 269 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 18 , 113 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 18 , 329 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 19 , 18 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 19 , 149 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 19 , 313 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 20 , 63 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 20 , 69 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 20 , 215 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 21 , 113 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 21 , 123 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 21 , 302 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 21 , 329 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 22 , 18 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 22 , 149 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 23 , 124 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 23 , 243 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 24 , 28 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 24 , 173 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 24 , 338 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 24 , 391 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 25 , 124 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 25 , 243 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 25 , 396 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 26 , 124 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 26 , 191 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 26 , 243 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 26 , 244 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 27 , 18 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 27 , 149 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 28 , 18 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 28 , 313 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 29 , 13 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 29 , 29 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 29 , 145 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 29 , 199 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 30 , 40 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 30 , 112 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 30 , 168 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 30 , 179 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 30 , 287 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 31 , 46 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 31 , 270 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 32 , 46 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 32 , 202 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 32 , 221 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 32 , 270 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 33 , 63 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 34 , 13 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 34 , 145 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 34 , 199 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 35 , 63 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 35 , 69 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 35 , 380 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 36 , 69 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 36 , 215 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 37 , 34 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 37 , 73 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 38 , 46 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 38 , 202 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 38 , 221 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 38 , 270 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 39 , 329 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 40 , 113 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 40 , 123 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 40 , 302 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 40 , 329 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 41 , 215 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 42 , 112 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 42 , 168 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 42 , 287 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 43 , 34 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 43 , 73 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 43 , 111 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 43 , 269 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 44 , 123 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 44 , 302 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 44 , 329 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 45 , 13 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 45 , 29 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 45 , 145 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 45 , 199 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 46 , 145 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 47 , 202 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 47 , 221 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 47 , 270 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 48 , 86 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 48 , 105 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 48 , 229 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 48 , 271 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 48 , 290 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 49 , 229 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 49 , 271 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 49 , 290 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 49 , 362 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 50 , 105 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 50 , 229 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 50 , 271 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 50 , 290 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 50 , 388 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 50 , 394 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 51 , 40 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 51 , 112 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 51 , 168 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 51 , 179 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 51 , 287 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 52 , 145 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 52 , 199 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 53 , 111 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 54 , 202 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 55 , 86 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 55 , 105 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 55 , 229 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 55 , 362 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 55 , 388 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 56 , 13 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 56 , 29 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 57 , 29 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 57 , 199 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 58 , 40 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 58 , 112 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 58 , 168 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 58 , 179 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 59 , 149 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 59 , 313 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 60 , 229 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 60 , 271 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 60 , 362 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 60 , 388 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 60 , 394 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 61 , 63 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 61 , 69 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 61 , 215 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 62 , 28 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 62 , 44 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 62 , 173 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 62 , 391 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 63 , 69 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 63 , 215 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 64 , 46 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 64 , 202 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 64 , 221 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 65 , 113 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 65 , 329 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 66 , 124 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 66 , 191 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 66 , 243 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 66 , 396 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 67 , 18 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 67 , 313 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 68 , 28 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 68 , 44 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 68 , 173 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 68 , 338 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 69 , 69 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 69 , 215 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 69 , 380 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 70 , 13 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 70 , 29 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 71 , 34 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 71 , 73 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 71 , 111 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 71 , 269 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 72 , 111 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 72 , 269 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 73 , 46 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 73 , 202 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 73 , 221 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 73 , 270 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 74 , 29 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 74 , 145 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 74 , 199 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 75 , 112 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 75 , 168 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 75 , 287 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 76 , 34 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 76 , 73 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 76 , 111 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 76 , 269 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 77 , 40 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 77 , 179 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 78 , 380 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 79 , 46 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 79 , 202 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 79 , 221 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 79 , 270 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 80 , 86 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 80 , 105 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 80 , 229 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 81 , 46 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 81 , 221 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 82 , 46 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 82 , 202 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 82 , 270 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 83 , 28 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 83 , 44 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 83 , 173 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 83 , 338 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 83 , 391 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 84 , 86 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 84 , 105 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 84 , 229 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 84 , 290 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 84 , 362 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 84 , 394 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 85 , 44 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 85 , 173 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 85 , 338 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 85 , 391 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 86 , 46 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 86 , 202 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 86 , 221 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 86 , 270 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 87 , 18 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 87 , 149 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 88 , 13 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 88 , 29 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 88 , 145 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 88 , 199 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 89 , 123 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 89 , 302 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 89 , 329 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 90 , 113 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 90 , 123 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 91 , 13 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 91 , 145 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 91 , 199 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 92 , 18 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 92 , 149 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 92 , 313 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 93 , 13 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 93 , 145 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 94 , 40 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 94 , 112 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 94 , 179 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 94 , 287 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 95 , 229 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 95 , 271 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 95 , 290 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 95 , 362 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 95 , 388 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 96 , 13 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 96 , 29 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 96 , 145 , 1) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 97 , 28 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 97 , 338 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 97 , 391 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 98 , 40 , 4) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 98 , 112 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 98 , 168 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 98 , 179 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 98 , 287 , 5) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 99 , 28 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 99 , 44 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 99 , 173 , 3) ;
insert into order_menu ( orderlist_No, menu_No, count) values ( 99 , 391 , 2) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 100 , 46 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 100 , 221 , 3) ; 
insert into order_menu ( orderlist_No, menu_No, count) values ( 100 , 270 , 2) ; 


desc orderlist;

select count(*) from orderlist;

desc order_menu;

select count(*) from order_menu
;
;
